[package]
name = "terminusdb-bin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Build script for compiling TerminusDB from source"
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
terminusdb-client = { version = "0.1.0", path = "../client" }
terminusdb-schema = { version = "0.1.0", path = "../schema" }
tokio = { workspace = true, features = ["time"] }
url.workspace = true
uuid = { workspace = true, features = ["v4"] }

[build-dependencies]
which = "6.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "terminusdb"
path = "src/main.rs"

[target."cfg(unix)".dependencies]
libc = "0.2.178"
